---
- hosts: webserver
  remote_user: test1
  become: true
  tasks:
     - name: Install httpd package
       yum: name={{item}} state=installed
       with_items:
          - httpd
          - curl
          - telnet

