---
- hosts: '{{host}}' 
  remote_user: test1
  become: true
  vars:
       pkg: httpd
  vars_files:
      - abc.yml
  vars_prompt:
       - name: pkg
         prompt: Enter package name
         private: no
  tasks:
     - name: Install httpd package
       yum: name={{pkg}} state=installed
     - name: Install {{pkg1}} package
       yum: name={{pkg1}} state=installed
     - name: Install {{pkg}} package
       yum: name={{pkg}} state=installed
     - name: Copy index.html
       copy: src=index.html  dest=/var/www/html/index.html
     - name: Start {{pkg}} service
       service: name={{pkg}} state=started

